language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t douchebag15/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true douchebag15/complex-test npm test

after_success:
  - docker build -t douchebag15/multi-client ./client
  - docker build -t douchebag15/multi-nginx ./nginx
  - docker build -t douchebag15/multi-server ./server
  - docker build -t douchebag15/multi-worker ./worker
#Login to Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push to DockerHub
  - docker push douchebag15/multi-client
  - docker push douchebag15/multi-nginx
  - docker push douchebag15/multi-server
  - docker push douchebag15/multi-worker


